import React from 'react';
import { render, screen, waitFor, within } from '@testing-library/react';
import { BrowserRouter as Router } from 'react-router-dom';
import '@testing-library/jest-dom';
import FirstStep from '../FirstStep';
import {
  autoGeneratedKey,
  mockFetchedKeys,
} from '../../__tests__/content.fixtures';
import userEvent from '@testing-library/user-event';
import { createActivationKey } from '../../../../../api';
import { useActivationKeyPermissions } from '../../../../hooks/useActivationKeyPermissions';

jest.mock(
  '@redhat-cloud-services/frontend-components-utilities/interceptors',
  () => ({
    __esModule: true,
    useAxiosWithPlatformInterceptors: () => require('axios'),
  })
);

jest.mock('../../../../../api');

jest.mock('../../../../hooks/useActivationKeyPermissions', () => ({
  useActivationKeyPermissions: jest.fn(),
}));

describe('FirstStep', () => {
  const handleFetchKeys = jest.fn();
  const setIsModalOpen = jest.fn();
  const setSelectedKey = jest.fn();
  const setStep = jest.fn();

  beforeEach(() => {
    // Default: user has both read and write permissions
    useActivationKeyPermissions.mockReturnValue({
      data: {
        canReadActivationKeys: true,
        canWriteActivationKeys: true,
      },
      isLoading: false,
    });
  });

  it('should display activation key', async () => {
    render(
      <Router>
        <FirstStep
          handleFetchKeys={handleFetchKeys}
          keys={mockFetchedKeys}
          selectedKey={mockFetchedKeys[0]}
          setIsModalOpen={setIsModalOpen}
          setSelectedKey={setSelectedKey}
          setStep={setStep}
          step={0}
        />
      </Router>
    );

    expect(
      screen.getByRole('button', {
        name: /activation-key-1/i,
      })
    ).toBeVisible();

    expect(
      screen.queryAllByRole('button', {
        name: /activation-key-2/i,
      })
    ).toHaveLength(0);

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /show selected activation key/i,
        })
      )
    );

    const region = screen.getByRole('region', {
      name: /show selected activation key/i,
    });

    expect(within(region).getByText(/activation-key-1/i)).toBeVisible();

    expect(screen.getByText(/8\.8/i)).toBeVisible();
  });

  it('should render activation key dropdown', async () => {
    render(
      <Router>
        <FirstStep
          handleFetchKeys={handleFetchKeys}
          keys={mockFetchedKeys}
          selectedKey={mockFetchedKeys[0]}
          setIsModalOpen={setIsModalOpen}
          setSelectedKey={setSelectedKey}
          setStep={setStep}
          step={0}
        />
      </Router>
    );

    expect(screen.queryAllByText(/activation-key-2/i)).toHaveLength(0);

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /activation-key-1/i,
        })
      )
    );

    expect(
      screen.getByRole('option', {
        name: /activation-key-1/i,
      })
    ).toBeVisible();

    expect(
      screen.getByRole('option', {
        name: /activation-key-2/i,
      })
    ).toBeVisible();
  });

  it('should handle activation key select', async () => {
    render(
      <Router>
        <FirstStep
          handleFetchKeys={handleFetchKeys}
          keys={mockFetchedKeys}
          selectedKey={mockFetchedKeys[0]}
          setIsModalOpen={setIsModalOpen}
          setSelectedKey={setSelectedKey}
          setStep={setStep}
          step={0}
        />
      </Router>
    );

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /activation-key-1/i,
        })
      )
    );

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('option', {
          name: /activation-key-2/i,
        })
      )
    );

    expect(setSelectedKey).toHaveBeenCalledWith(mockFetchedKeys[1]);
    expect(setStep).toHaveBeenCalledWith(1);
  });

  it('should handle activation key select with newly created key', async () => {
    render(
      <Router>
        <FirstStep
          createdKeyName={mockFetchedKeys[1].name}
          handleFetchKeys={handleFetchKeys}
          keys={mockFetchedKeys}
          selectedKey={mockFetchedKeys[0]}
          setIsModalOpen={setIsModalOpen}
          setSelectedKey={setSelectedKey}
          setStep={setStep}
          step={0}
        />
      </Router>
    );

    expect(setSelectedKey).toHaveBeenCalledWith(mockFetchedKeys[1]);
    expect(setStep).toHaveBeenCalledWith(1);
  });

  it('should handle create activation key', async () => {
    render(
      <Router>
        <FirstStep
          handleFetchKeys={handleFetchKeys}
          keys={mockFetchedKeys}
          selectedKey={mockFetchedKeys[0]}
          setIsModalOpen={setIsModalOpen}
          setSelectedKey={setSelectedKey}
          setStep={setStep}
          step={0}
        />
      </Router>
    );

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /activation-key-1/i,
        })
      )
    );

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /create activation key/i,
        })
      )
    );

    expect(setIsModalOpen).toHaveBeenCalledWith(true);
  });

  it.skip('should handle auto-generate activation key', async () => {
    createActivationKey.mockImplementation(async () => {
      return { body: autoGeneratedKey };
    });

    render(
      <Router>
        <FirstStep
          handleFetchKeys={handleFetchKeys}
          keys={mockFetchedKeys}
          selectedKey={mockFetchedKeys[0]}
          setIsModalOpen={setIsModalOpen}
          setSelectedKey={setSelectedKey}
          setStep={setStep}
          step={0}
        />
      </Router>
    );

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /activation-key-1/i,
        })
      )
    );

    await waitFor(() =>
      userEvent.click(
        screen.getByRole('button', {
          name: /auto-generate activation key/i,
        })
      )
    );

    expect(setSelectedKey).toHaveBeenCalledWith(autoGeneratedKey);
    expect(setStep).toHaveBeenCalledWith(1);
  });

  describe('Permissions', () => {
    it('should show no access message when user has no read permission', async () => {
      useActivationKeyPermissions.mockReturnValue({
        data: {
          canReadActivationKeys: false,
          canWriteActivationKeys: false,
        },
        isLoading: false,
      });

      render(
        <Router>
          <FirstStep
            handleFetchKeys={handleFetchKeys}
            keys={mockFetchedKeys}
            selectedKey="Select activation key"
            setIsModalOpen={setIsModalOpen}
            setSelectedKey={setSelectedKey}
            setStep={setStep}
            step={0}
          />
        </Router>
      );

      // Click to open dropdown
      await waitFor(() =>
        userEvent.click(
          screen.getByRole('button', {
            name: /select activation key/i,
          })
        )
      );

      // Should show no access message
      expect(
        screen.getByText(/you do not have access to view activation keys/i)
      ).toBeVisible();

      // Should NOT show create/auto-generate buttons
      expect(
        screen.queryByRole('button', {
          name: /create activation key/i,
        })
      ).not.toBeInTheDocument();
    });

    it('should disable create/auto-generate buttons when user has read but no write permission', async () => {
      useActivationKeyPermissions.mockReturnValue({
        data: {
          canReadActivationKeys: true,
          canWriteActivationKeys: false,
        },
        isLoading: false,
      });

      render(
        <Router>
          <FirstStep
            handleFetchKeys={handleFetchKeys}
            keys={mockFetchedKeys}
            selectedKey={mockFetchedKeys[0]}
            setIsModalOpen={setIsModalOpen}
            setSelectedKey={setSelectedKey}
            setStep={setStep}
            step={0}
          />
        </Router>
      );

      // Click to open dropdown
      await waitFor(() =>
        userEvent.click(
          screen.getByRole('button', {
            name: /activation-key-1/i,
          })
        )
      );

      // Should show activation keys
      expect(
        screen.getByRole('option', {
          name: /activation-key-1/i,
        })
      ).toBeVisible();

      // Buttons should exist but be disabled
      const createButton = screen.getByRole('button', {
        name: /create activation key/i,
      });
      const autoGenerateButton = screen.getByRole('button', {
        name: /auto-generate activation key/i,
      });

      expect(createButton).toBeDisabled();
      expect(autoGenerateButton).toBeDisabled();
    });

    it('should show loading state while permissions are loading', async () => {
      useActivationKeyPermissions.mockReturnValue({
        data: null,
        isLoading: true,
      });

      render(
        <Router>
          <FirstStep
            handleFetchKeys={handleFetchKeys}
            keys={undefined}
            selectedKey="Select activation key"
            setIsModalOpen={setIsModalOpen}
            setSelectedKey={setSelectedKey}
            setStep={setStep}
            step={0}
          />
        </Router>
      );

      // Click to open dropdown
      await waitFor(() =>
        userEvent.click(
          screen.getByRole('button', {
            name: /select activation key/i,
          })
        )
      );

      // Should show loading skeletons (from loadingActivationKeys)
      const options = screen.getAllByRole('option');
      expect(options.length).toBeGreaterThan(0);
    });
  });
});
