extends: 
  - "@redhat-cloud-services/eslint-config-redhat-cloud-services"
  - 'plugin:cypress/recommended'
  - 'plugin:testing-library/react'
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
rules:
  rulesdir/forbid-pf-relative-imports: 'off'