apiVersion: v1
kind: Template
metadata:
  name: registration-assistant
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: registration-assistant
    spec:
      envName: ${ENV_NAME}
      title: registration-assistant
      deploymentRepo: https://github.com/RedHatInsights/registration-assistant
      frontend:
        paths:
          - /apps/registration
        akamaiCacheBustPaths:
         - /apps/registration/fed-mods.json
      API:
        versions:
          - v1
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/registration/fed-mods.json"
        modules:
          - id: "registration-assistant"
            module: "./RootApp"
            routes:
              - pathname: /insights/registration-assistant
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/registration-assistant
